config/routes.rb
Rails.application.routes.draw do
  namespace :tasks do
    get "completed/new"
  end
  root 'tasks#index'

  resource :session
  resources :passwords, param: :token
  resources :tasks, only: %i[index show new create edit update destroy] do
    resource :completed, only: %i[create destroy], module: :tasks
    resource :start, only: %i[create destroy], module: :tasks
    resource :stopped, only: %i[create destroy], module: :tasks
  end
  resources :daily_reports, only: %i[index show new create edit update]
  resources :kpt_items, only: %i[index new create show edit update] do
    member do
      get 'suggest_try'
      get 'dig_into_problem'
    end
  end

  post 'kpt_items/suggest_try', to: 'kpt_items#suggest_try'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  scope :incomplete, -> { where(completed_at: nil) }
  scope :complete, -> { where.not(completed_at: nil) }
  scope :latest_completed, -> { order(completed_at: :desc) }
  scope :latest_created, -> { order(created_at: :desc) }

  def duration
    return nil unless start_at && completed_at

    ((completed_at - start_at) / 60).to_i
  end
end

app/controllers/tasks/completeds_controller.rb
class Tasks::CompletedsController < ApplicationController
  before_action :set_task, only: %i[create destroy]

  def create
    @task.update!(completed_at: Time.current)
    redirect_to task_path(@task)
  end

  def destroy
    @task.update!(completed_at: nil)
    redirect_to task_path(@task)
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/tasks/starts_controller.rb
class Tasks::StartsController < ApplicationController
  def create
    @task = Task.find(params[:task_id])
    @task.update!(start_at: Time.current)
    redirect_to task_path(@task)
  end
end

app/controllers/tasks/stoppeds_controller.rb
class Tasks::StoppedsController < ApplicationController
  def create
    @task = Task.find(params[:task_id])
    @task.update!(stopped_at: Time.current)
    redirect_to task_path(@task)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = if params[:completed].present?
               Task.complete.latest_completed
             else
               Task.incomplete.latest_created
             end
    @task = Current.user.tasks.build
  end

  def show
  end

  def new
    @task = Current.user.tasks.build
  end

  def create
    @task = Current.user.tasks.build(tasks_params)
    if @task.save
      redirect_to tasks_path, notice: '登録しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(tasks_params)
      redirect_to task_path(@task), notice: '変更しました'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy!
    redirect_to tasks_path, notice: '削除しました'
  end

  private

  def tasks_params
    params.expect(task: %i[title description completed_at priority])
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/views/tasks/_form.html.haml
.container
  .card
    .card-body
      = simple_form_for task do |f|
        = render 'shared/error_messages', resource: task
        = f.input :title
        = f.input :description
        .text-center
          = f.submit class: 'btn btn-primary'

app/views/tasks/edit.html.haml
%h2.text-center.mt-4.mb-4 タスク編集
.container.mb-4
  = button_to '削除', task_path(@task), method: :delete, data: { turbo_confirm: '本当に削除しますか？' }, class: 'btn btn-outline-danger'
= render 'tasks/form', task: @task

app/views/tasks/index.html.haml
%h2.text-center.mt-4 やること一覧
.container
  .row
    .col-6
      .card
        .card-body
          = simple_form_for @task do |f|
            = render 'shared/error_messages', resource: @task
            = f.input :title
            = f.input :description
            .text-center
              = f.submit class: 'btn btn-primary'
    .col-6
      %table.table.table-striped.table-hover
        %thead.table-light
          %tr
            %th やること
            %th 登録日
        %tbody
          - @tasks.each do |task|
            %tr
              %td= link_to task.title, task_path(task), class: 'text-decoration-none'
              %td= task.created_at.strftime('%Y/%m/%d')

app/views/tasks/new.html.haml
%h2.text-center.mt-4.mb-4 タスク登録
= render 'tasks/form', task: @task

app/views/tasks/show.html.haml
%h2.text-center.mt-4 タスク詳細

.container.mt-4
  = link_to '編集', edit_task_path(@task), class: 'btn btn-sm btn-outline-primary mb-4'
  .card
    .card-header.bg-primary.text-white
      %h2.mb-0= @task.title
    .card-body
      .row
        .col-md-8
          %h4.card-title 詳細:
          %p.card-text= @task.description
          %h4.mt-4 作成日:
          %p.card-text= l(@task.created_at, format: :default)
          %h4.mt-4 作業時間:
          %p.card-text #{@task.duration}分
          .d-flex
            %td
              - if @task.start_at.present? && @task.completed_at.nil?
                = button_to 'タスク中断', task_stopped_path(@task), method: :post, class: 'btn btn-sm btn-outline-warning me-2'
              - elsif @task.completed_at.nil?
                = button_to 'タスク開始', task_start_path(@task), method: :post, class: 'btn btn-sm btn-outline-success me-2'
            %td
              - if @task.completed_at.nil?
                = button_to 'タスク完了', task_completed_path(@task), method: :post, class: 'btn btn-sm btn-outline-primary me-2'
              - else
                = button_to '未完了に戻す', task_completed_path(@task), method: :delete, class: 'btn btn-sm btn-outline-danger me-2'