config/routes.rb
Rails.application.routes.draw do
  namespace :tasks do
    get "completed/new"
  end
  root 'tasks#index'

  resource :session
  resources :passwords, param: :token
  resources :tasks, only: %i[index show new create edit update destroy] do
    resource :completed, only: %i[create destroy], module: :tasks
    resource :start, only: %i[create destroy], module: :tasks
    resource :stopped, only: %i[create destroy], module: :tasks
  end
  resources :daily_reports, only: %i[index show new create edit update]
  resources :kpt_items, only: %i[index new create show edit update] do
    member do
      get 'suggest_try'
      get 'dig_into_problem'
    end
  end

  post 'kpt_items/suggest_try', to: 'kpt_items#suggest_try'
end

app/models/kpt_item.rb
class KptItem < ApplicationRecord
  belongs_to :user
end

app/controllers/kpt_items_controller.rb
class KptItemsController < ApplicationController
  before_action :set_kpt_item, only: %i[show edit update suggest_try dig_into_problem]

  def index
    @kpt_items = KptItem.order(created_at: :desc)
  end

  def show
    @kpt_item = KptItem.find(params[:id])
  end

  def new
    @kpt_item = Current.user.kpt_items.build
  end

  def create
    @kpt_item = Current.user.kpt_items.build(kpt_item_params)
    if @kpt_item.save
      redirect_to edit_kpt_item_path(@kpt_item), notice: '作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @kpt_item.update(kpt_item_params)
      redirect_to kpt_item_path(@kpt_item), notice: '作成しました'
    else
      render :new
    end
  end


  def suggest_try
    problem = @kpt_item.problem

    client = OpenAI::Client.new

    prompt = "#{problem}がKPT法のProblemです。Tryのみを提案してください。"
    response = client.chat(
      parameters: {
        model: 'gpt-4o',
        messages: [
          {role: "system", content: "You are a helpful assistant. Be sure to reply in Japanese."},
          { role: 'user', content: prompt },
        ],
        max_tokens: 200,
      }
    )

    @try_suggestion = response.dig('choices', 0, 'message', 'content').strip


    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def dig_into_problem
    problem = @kpt_item.problem

    client = OpenAI::Client.new

    prompt = "#{problem}がKPT法のProblemです。Problemを掘り下げてください。"
    response = client.chat(
      parameters: {
        model: 'gpt-4o',
        messages: [
          {role: "system", content: "You are a helpful assistant. Be sure to reply in Japanese."},
          { role: 'user', content: prompt },
        ],
        max_tokens: 200,
      }
    )

    @dig_into = response.dig('choices', 0, 'message', 'content').strip

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  private

  def kpt_item_params
    params.expect(kpt_item: %i[content keep problem try])
  end

  def set_kpt_item
    @kpt_item = KptItem.find(params[:id])
  end
end

app/views/kpt_items/_form.html.haml
.card-body
  = simple_form_for kpt_item do |f|
    = render 'shared/error_messages', resource: kpt_item
    = f.input :keep
    = f.input :problem
    = f.input :try
    .text-center
      = f.button :submit, class: 'btn btn-primary'

app/views/kpt_items/dig_into_problem.turbo_stream.haml
= turbo_stream.replace "dig_into_frame" do
  #dig_into
  - if @dig_into.present?
    %p= markdown_to_html(@dig_into)

app/views/kpt_items/edit.html.haml
%h2.text-center.mt-4.mb-4 KPT編集
.container
  .card
    .card-body
      = render 'kpt_items/form', kpt_item: @kpt_item
      - if @kpt_item.persisted?
        = button_to 'Problemを深堀る', dig_into_problem_kpt_item_path(@kpt_item, format: :turbo_stream),
          method: :get, data: { turbo_frame: 'dig_into_frame' }, class: 'btn btn-outline-dark mb-2'
        %turbo-frame#dig_into_frame
        = button_to 'Tryを提案', suggest_try_kpt_item_path(@kpt_item, format: :turbo_stream),
          method: :get, data: { turbo_frame: 'try_suggestion_frame' }, class: 'btn btn-outline-dark'
        %turbo-frame#try_suggestion_frame

app/views/kpt_items/index.html.haml
%h2.text-center.mt-4.mb-4 KPT一覧
.container
  = link_to '登録', new_kpt_item_path, class: 'btn btn-primary mb-4'
  %ul
    - @kpt_items.each do |kpt|
      %li
        = link_to "#{l(kpt.created_at, format: :default)}に作成されたKPT", kpt_item_path(kpt)

app/views/kpt_items/new.html.haml
%h2.text-center.mt-4.mb-4 KPT作成
.container
  .card
    .card-body
      = render 'kpt_items/form', kpt_item: @kpt_item

      #suggestion
        - if @try_suggestion.present?
          %p= @try_suggestion

app/views/kpt_items/show.html.haml
%h2.text-center.mt-4.mb-4 KPT
.container.mb-4
  = link_to '編集', edit_kpt_item_path(@kpt_item), class: 'btn btn-sm btn-outline-primary mb-4'
  .card
    .card-body
      %h4.card-title K
      = markdown_to_html(@kpt_item.keep)
      %h4.card-title P
      = markdown_to_html(@kpt_item.problem)
      %h4.card-title T
      = markdown_to_html(@kpt_item.try)

app/views/kpt_items/suggest_try.turbo_stream.haml
= turbo_stream.replace "try_suggestion_frame" do
  #suggestion
  - if @try_suggestion.present?
    %p= markdown_to_html(@try_suggestion)