config/routes.rb
Rails.application.routes.draw do
  namespace :tasks do
    get "completed/new"
  end
  root 'tasks#index'

  resource :session
  resources :passwords, param: :token
  resources :tasks, only: %i[index show new create edit update destroy] do
    resource :completed, only: %i[create destroy], module: :tasks
    resource :start, only: %i[create destroy], module: :tasks
    resource :stopped, only: %i[create destroy], module: :tasks
  end
  resources :daily_reports, only: %i[index show new create edit update]
  resources :kpt_items, only: %i[index new create show edit update] do
    member do
      get 'suggest_try'
      get 'dig_into_problem'
    end
  end

  post 'kpt_items/suggest_try', to: 'kpt_items#suggest_try'
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
  belongs_to :user
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  before_action :set_daily_report, only: %i[show edit update]

  def index
    @daily_reports = DailyReport.order(created_at: :desc)
  end

  def show
  end

  def new
    @daily_report = Current.user.daily_reports.build
  end

  def create
    @daily_report = Current.user.daily_reports.build(daily_report_params)
    if @daily_report.save
      redirect_to daily_report_path(@daily_report), notice: '作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @daily_report.update(daily_report_params)
      redirect_to daily_report_path(@daily_report), notice: '編集しました'
    else
      render :edit
    end
  end

  private

  def daily_report_params
    params.expect(daily_report: %i[content memo])
  end

  def set_daily_report
    @daily_report = Current.user.daily_reports.find(params[:id])
  end
end

app/views/daily_reports/_form.html.haml
.container
  .card
    .card-body
      = simple_form_for daily_report do |f|
        = render 'shared/error_messages', resource: daily_report
        - if disciple.present?
          = f.input :memo
        - else
          = f.input :content
        .text-center
          = f.submit class: 'btn btn-primary'

app/views/daily_reports/edit.html.haml
%h2.text-center.mt-4.mb-4=link_to '日報編集', edit_daily_report_path(@daily_report, disciple: true), class: 'text-decoration-none text-black'
= render 'daily_reports/form', daily_report: @daily_report, disciple: params[:disciple]

app/views/daily_reports/index.html.haml
%h2.text-center.mt-4.mb-4 日報一覧
.container
  = link_to '登録', new_daily_report_path, class: 'btn btn-primary mb-4'
  %ul
    - @daily_reports.each do |report|
      %li
        = link_to "#{l(report.created_at, format: :default)}に作成された日報", daily_report_path(report)

app/views/daily_reports/new.html.haml
%h2.text-center.mt-4.mb-4 日報作成
= render 'daily_reports/form', daily_report: @daily_report, disciple: params[:disciple]

app/views/daily_reports/show.html.haml
%h2.text-center.mt-4.mb-4=link_to '日報', edit_daily_report_path(@daily_report, disciple: true), class: 'text-decoration-none text-black'
.container
  - if Current.user == @daily_report.user
    = link_to '編集', edit_daily_report_path(@daily_report), class: 'btn btn-outline-primary mb-4'
    .card
      .card-body
        = markdown_to_html(@daily_report.content)
        - if @daily_report.memo.present?
          %h1 良かったこと
          = markdown_to_html(@daily_report.memo)
  - else
    .card
      .card-body
        = markdown_to_html(@daily_report.content)