config/routes.rb
Rails.application.routes.draw do
  namespace :tasks do
    get "completed/new"
  end
  root 'tasks#index'

  resource :session
  resources :passwords, param: :token
  resources :tasks, only: %i[index show new create edit update destroy] do
    resource :completed, only: %i[create destroy], module: :tasks
    resource :start, only: %i[create destroy], module: :tasks
    resource :stopped, only: %i[create destroy], module: :tasks
  end
  resources :daily_reports, only: %i[index show new create edit update]
  resources :kpt_items, only: %i[index new create show edit update] do
    member do
      get 'suggest_try'
      get 'dig_into_problem'
    end
  end

  post 'kpt_items/suggest_try', to: 'kpt_items#suggest_try'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Work Tool"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
  %body
    - if notice
      .alert.alert-success.mb-0
        = notice
    - if alert
      .alert.alert-danger.mb-0
        = alert
    %nav.navbar.navbar-expand-sm.navbar-dark.bg-dark.mb-3
      %h2.text-white.ms-2
        = link_to 'タスクツール', tasks_path, class: 'text-decoration-none text-white'
      .ms-auto.me-2
        - if authenticated?
          .d-inline-block
            = link_to '完了済みタスク', tasks_path(completed: true), class: 'text-white text-decoration-none me-2'
          .d-inline-block
            = link_to '日報', daily_reports_path, class: 'text-white text-decoration-none me-2'
          .d-inline-block
            = link_to 'KPT', kpt_items_path, class: 'text-white text-decoration-none me-2'
          .d-inline-block
            = button_to 'ログアウト', session_path, method: :delete, class: 'btn btn-outline-danger'
    = yield